### PR TITLE
Highlight partial words

### PR DESCRIPTION
**Pull request by moses-v51**
Updating so that partial words can be highlighted and adding bower.json
file

### CODE REVIEW

**Comment by jrust** [comment]
Would it be worth it to make was a directive option, `highlight-partial` or something?  That way we could see if it could be merged back to original repo.

**Comment by jrust** [comment]
Though did just see that it's 2 years old, so maybe not worth the effort if we don't think we'll ever want the word-based version.

**Comment by moses-v51** [comment]
At two years old, I really don't expect any updates from this library.  I chose it as it was small and did what we needed with only minor updates.  Mark specifically asked for partial word matching and it seems like a good idea, though anything can change!

**Comment by jrust** [comment]
👍

**Comment by moses-v51** [comment]
Shockingly, the library owner accepted my PR!  Now I have to figure out how to update the git-endpoint on bower...

**Review by jrust — APPROVED** [review]

**Pull request merged**
